### ISSUE TITLE
Support no_std

### ISSUE THREAD

**Issue by tomaka** [paritytech/jsonrpsee#1]
Blocked by https://github.com/serde-rs/json/issues/362

**Comment by tomaka** [comment]
Also blocked by https://github.com/rust-lang/rust/issues/56974

**Comment by Xanewok** [comment]
serde_json with `alloc`-only support landed in 1.0.45 - https://github.com/serde-rs/json/pull/606#issuecomment-577445497

**Comment by yjhmelody** [comment]
At leat `jsonrpsee-types` need to support no_std

**Comment by niklasad1** [comment]
So this hasn't been a priority because all transports in jsonrpsee requires std even the `WASM client`. 
It requires some major refactoring of the error types to be feature-gated and so on.

However, if you can explain why you need `no_std` in jsonrpsee that would help us to understand why we should support it.

**Comment by yjhmelody** [comment]
> So this hasn't been a priority because all transports in jsonrpsee requires std even the `WASM client`. It requires some major refactoring of the error types to be feature-gated and so on.
> 
> However, if you can explain why you need `no_std` in jsonrpsee that would help us to understand why we should support it.

Maybe substrate offchain worker need it ?

**Comment by jsdw** [comment]
For now, this isn't a priority for us since we don't need it internally, and so I'll close it off.
