### ISSUE TITLE
Get connection ID in rpc handler

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#1014]
So that it is possible to rate limit message per seconds per connection

**Comment by bkchr** [comment]
@niklasad1 AFAIU @xlc would like to contribute some features like this one, can you make sure he gets the help that he needs?

**Comment by niklasad1** [comment]
Like I said before the RPC handler is not exposed by this library by design.

https://github.com/paritytech/jsonrpsee/issues/918 would solve this issue as well as some similar issues raised recently.

**Comment by xlc** [comment]
I am not 100% following. How is TwoerService going to help?

All I need is to make this NOT ignore the connect id parameter

https://github.com/paritytech/jsonrpsee/blob/18ee2122ec84392c915bfe26bea73c30f41a7a6d/core/src/server/rpc_module.rs#L669

It could be a simple change by adjusting the callback function signature to include connection ID, which will be a breaking change. Or add new register method with callback takes connection ID.

**Comment by xlc** [comment]
I am not very familiar with Tower middleware but I don't think it applies here. It is not compatible with websocket frame data.

**Comment by niklasad1** [comment]
> It could be a simple change by adjusting the callback function signature to include connection ID, which will be a breaking change. 

The only way to do that is return connection ID from the method call but it makes no sense from our perspective as the server already knows that prior the call.

> Or add new register method with callback takes connection ID.

This won't work because register_method is done at initialization i.e, before the connection is established.

> I am not very familiar with Tower middleware but I don't think it applies here. It is not compatible with websocket frame data.

Ok, I will write down a better issue for it but yeah you are correct after the HTTP upgrade is completed. Then we have no use of tower but you could actually fetch the connection ID there and store somewhere/spawn a task in your proxy for each connection.
Not sure, I haven't really looked at your code.

To elaborate it would useful if you could add an example snippet code what you want to do then it we would understand better and could help out better.
