### ISSUE TITLE
shutdown server while there is connection does not work

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#1117]
I am upgrading jsonrpsee and identified a regression from our tests that shutdown server while there is existing connection doesn't work.

Shouldn't the server automatically terminate the connections when it is being told to shutdown?

#1116 is a failed test to demo this regression.

This is our test that got broken after upgrade https://github.com/AcalaNetwork/subway/blob/8021a32ec385607976597b4c49f09360903a91c4/src/client/tests.rs#L158

The expectation is that the unit test in #1116 should be passing.

**Comment by niklasad1** [comment]
> There was a bug before that the server didn't really gracefully shutdown i.e, regardless whether it had pending calls or not.

> Thus, we changed that if there are pending calls the server will stop (async fn stopped will return then) after those has been completed or that the connection is already closed by the client.

After looking at your code [this](https://github.com/AcalaNetwork/subway/blob/8021a32ec385607976597b4c49f09360903a91c4/src/client/mock.rs#L46) won't complete because it is waiting for message from channel in your test task. 

When the RPC handler (register_async_method) returns then the message is sent out on the socket but as you wait on a message in the RPC handler itself it won't reply to the call until a message is sent to the channel. Then you expect to stop the server with uncompleted RPC call and gracefully shutdown won't work.

Thus, if the `future `register_async_method` doesn't return the server can't be stopped gracefully and you need to change your code unfortunately.

With that said I don't regard this a jsonrpsee issue but it's tricky for sure.

**Comment by xlc** [comment]
I see. Any suggestion on how can I create a dummy server that accept a request and kill the connection without complete the request?

**Comment by niklasad1** [comment]
It's not really possible to terminate a connection with a pending call because of the graceful shutdown except if the client closes the connection.

New connections are rejected though after stop has been called.

I'm not sure whether we should add another stop API which doesn't enforce graceful shutdown.

**Comment by xlc** [comment]
Let’s say if we need a test in this repo for the ws client to test if it can correctly handle the case where server accepts the request but crashed before response. How would you do it?

**Comment by niklasad1** [comment]
We don't have such test in jsonrpsee but I would mock the JSON-RPC server similar to what we have [here](https://github.com/paritytech/jsonrpsee/blob/master/test-utils/src/mocks.rs#L148-#L153) and pass in an extra mpsc channel in the server that sends a message when the request has been ACK:ed (very similar what you already have)

Then just close down the server and assert that the ws client connection was terminated.
