### ISSUE TITLE
Connection failure logs

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [paritytech/jsonrpsee#1120]
Connection failure logs are emitted at `warn` level which becomes pretty spammy since they come from external clients disconnecting. Example log:
```
WARN connection: HTTP serve connection failed hyper::Error(IncompleteMessage) remote_addr=XXX conn_id=YYY
```
I see you [recently](https://github.com/paritytech/jsonrpsee/pull/1076) downgraded the connection log to `debug`, so I'm wondering if this warning should be treated similarly, or if this is actually a log we should look into?

We're still on jsonrpsee version 16.2 but I did not see this mentioned in PRs or release notes.

**Comment by niklasad1** [comment]
These "connection failures" are in most cases (all I have seen) because the client closed down connection before the connection could be established (which is the case for you as well, so you could ignore that)

Thus, we downgraded these logs because they are confusing and causes more harm than good but could potentially be an issue in "hyper or in our code" if the client wasn't disconnected.

It's possible to debug such cases but with more verbose logging.

**Comment by niklasad1** [comment]
It's included in https://github.com/paritytech/jsonrpsee/releases/tag/v0.17.0, under changed.

**Comment by Mirko-von-Leipzig** [comment]
Apologies, I think maybe my issue wasn't very clear. You still have [this](https://github.com/paritytech/jsonrpsee/blob/master/server/src/server.rs#L823-L825) connection log at `warn` level, which in our case is triggering quite often.

I was suggesting maybe it should also be downgraded to `debug` level.

**Comment by niklasad1** [comment]
Ah, ok I see let's do it :)

**Comment by Mirko-von-Leipzig** [comment]
Thanks, I appreciate the prompt response!
