### ISSUE TITLE
JSON RPC + HTTP standard endpoints

### ISSUE THREAD

**Issue by marioiordanov** [paritytech/jsonrpsee#1125]
Can jsonrpsee be used with other http framework, so the server can process requests both as json rpc on route /rpc and standard http get, post requests on any other route

**Comment by marioiordanov** [comment]
Does this work for having JSON RPC methods that return a response to /rpc route and also simple http methods that don't comply with JSON RPC request format. For example:
post request to /rpc are handled by jsonrpsee::RpcModule
get, post, put, etc. to /, /home, /index are handled by axum,warp,etc.

**Comment by niklasad1** [comment]
No, it doesn't work with any existing web framework AFAIK.

I haven't used axum/warp that much to know whether you can wrap the RpcModule inside a handler for `/rpc` somehow.

Otherwise, you have to run your jsonrpsee server and add middleware to route them to the axum/warp endpoint...

Also we got https://github.com/paritytech/jsonrpsee/issues/1016 which might help with this....

**Comment by niklasad1** [comment]
Closing this issue because jsonrpsee isn't a web framework and this is out of scope of this project.

Thus, anyone could use the `RpcModule` and implement `jsonrpc-axum` or `jsonrpc-warp` or similar wrapper crates I reckon.
