### ISSUE TITLE
High memory consumption after update from 0.16 to 0.18

### ISSUE THREAD

**Issue by ok-ul-ch** [paritytech/jsonrpsee#1150]
### Summary
After the update to 0.18, we've started to observe weird memory behavior in our app, which looks like a memory leak to me. 

I've used code from `examples/examples/tokio_console.rs` to reproduce the issue, it starts `jsonrpsee` server, registers dummy method and waits. Client sends requests sequentially and receives 405 Status Code.

<details>
  <summary>Server code</summary>

```
use std::net::SocketAddr;

use jsonrpsee::server::ServerBuilder;
use jsonrpsee::RpcModule;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
	let _ = run_server().await?;

	futures::future::pending().await
}

async fn run_server() -> anyhow::Result<SocketAddr> {
	let server = ServerBuilder::default().build("127.0.0.1:9944").await?;
	let mut module = RpcModule::new(());

	//Use for 0.18
	//module.register_method("say_hello", |_, _| "lo")?;
	module.register_method("say_hello", |_, _| Ok("lo"))?;

	let addr = server.local_addr()?;
	let handle = server.start(module)?;

	// In this example we don't care about doing a stopping the server so let it run forever.
	// You may use the `ServerHandle` to shut it down or manage it yourself.
	tokio::spawn(handle.stopped());

	Ok(addr)
}
```
</details>
<details>
  <summary>Client code</summary>

```
use std::time::Duration;

#[tokio::main]
async fn main() {
    tokio::spawn(async {
        loop {
            let _ = dbg!(reqwest::get("http://127.0.01:9944").await);

            tokio::time::sleep(Duration::from_millis(10)).await
        }
    });

    futures::future::pending().await
}
```
</details>

### STR
1. Run server code sample for both: `0.16.2` and `0.18.2` versions of `jsonrpsee`;
2. Run client;
3. Observe memory usage.

### Behavior
`0.16.2` - memory usage is constant, as expected. [See heaptrack profile report](https://github.com/paritytech/jsonrpsee/files/12027228/jsonrpsee16.gz)
![image](https://github.com/paritytech/jsonrpsee/assets/17966148/9064967e-711c-4a79-9bd5-dbae59934dde)

`0.18.2` - memory usage grows over time. [See heaptrack profile report](https://github.com/paritytech/jsonrpsee/files/12027235/jsonrpsee18.gz)
![image](https://github.com/paritytech/jsonrpsee/assets/17966148/e8c6f499-a8bc-4720-9e0a-a05f5639bc05)

**Comment by okulch-hence** [comment]
It looks like the issue is in the fact that futures running connections are not dropped.
Connections are inserted [here](https://github.com/paritytech/jsonrpsee/blob/bdd1213ea5769e7bd1cead5d5ae9d42a4d3ab1a9/server/src/server.rs#L769C1-L769C1) and [here](https://github.com/paritytech/jsonrpsee/blob/bdd1213ea5769e7bd1cead5d5ae9d42a4d3ab1a9/server/src/server.rs#L802) AND not removed in the server's loop [here](https://github.com/paritytech/jsonrpsee/blob/bdd1213ea5769e7bd1cead5d5ae9d42a4d3ab1a9/server/src/server.rs#L144)



Flamegraph reporting "leak" 
![image](https://github.com/paritytech/jsonrpsee/assets/119855964/622b4e39-dc8b-4d5f-bc9c-917a48251bbd)

**Comment by aoudiamoncef** [comment]
Hi @mralexes, have you tested with `max_connections = 1` ?

**Comment by mralexes** [comment]
@aoudiamoncef yup, same behavior
