### ISSUE TITLE
WebSocket request rate limiting

### ISSUE THREAD

**Issue by kukabi** [paritytech/jsonrpsee#1157]
It would be a useful feature to be able to limit the number of WebSocket requests than can be made through an already open connection. It's a requirement for Substrate RPC providers, which otherwise should be solved through a custom WS proxy.

Is it something you guys are working on, or otherwise would you be open to PRs? Some direction would be great for the latter.

Thanks!

**Comment by niklasad1** [comment]
Hey @kukabi 

Previously jsonrpsee introduced something called `resource limiting` but we removed  it in favor of backpressure instead to limit the memory usage because it became to complicated to use for subscriptions etc. However, that won't rate limit the way you want.

In addition one could also use rate limiting based with tower middleware but it only works on the HTTP layer but that's not question just wanted to clarify.....

The ideal solution is to introduce a JSON-RPC middleware to accomplish that.

Thus we would want to have trait such as (this is a very rough template):

```rust
trait RpcMiddleware  {
    ///
    /// Returns `Some` if the RPC call shall be handled otherwise `None`.
    fn on_request(&self, req: JsonRpcRequest) -> Option<JsonRpcRequest> {...} 
}
```

Based on that users can easily implement that rate limiting or custom logic to deny requests.

/cc @jsdw @lexnv thoughts ideas?

**Comment by ggawryal** [comment]
Hey, any updates on this? I'd be also interested in such a functionality, and the proposed template would work for me.

**Comment by kostekIV** [comment]
@niklasad1 I could help with this if nobody is currently working on that. Would you accept a contribution with such middleware?

**Comment by niklasad1** [comment]
Hey @kostekIV, thanks for the suggestion but I have looked into this more thorough now and it's a quite involved because introducing this we want to get rid of the `Logger middleware` and replace it with a new middleware which is more flexible for folks to implement custom logic on-top of it including logging for prometheus metrics etc.

Thus, the two alternatives are as follows:

a)

```rust
pub trait JsonRpcMiddleware {
	/// The future response value.
	type Future: Future<Output = JsonRpcResponse>;

	/// Process JSON-RPC call and return the response async.
	///
	/// NOTE: config: includes connection ID etc to associate the JSON-RPC call
	/// with a certain connection.
	fn call(&mut self, req: JsonRpcRequest, cfg: Config) -> Self::Future;
}

```

This suggestion is hard to implement because it requires a bunch of stuff to be composable inside jsonrpsee
i.e as TowerService or very similar to it but a really clean solution.

b)

```rust
pub trait JsonRpcMiddleware {
	/// Process the request.
	///
	/// Returns `Err(method response)` if request shouldn't be handled and
        /// and method call is answered with `method response` otherwise the 
        /// call is further processed.
	///
	/// NOTE: config: includes connection ID etc to associate the JSON-RPC call
	/// with a certain connection.
	fn on_request(&mut self, req: JsonRpcRequest, config: &Config) -> Result<JsonRpcRequest, JsonRpcResponse>;

	/// Process the response
	fn on_response(&mut self, response: JsonRpcResponse, config: &Config) -> JsonRpcResponse;
}
```

Thus, I think it's better that we implement because it's plenty of changes needed sadly
