### ISSUE TITLE
Can we unsubscribe just use id?

### ISSUE THREAD

**Issue by rise0chen** [paritytech/jsonrpsee#1272]
Don't use method name, just use id.

For example:
```json
{ 
  "jsonrpc": "2.0",
  "method": "unsubscribe_by_id",
  "params": [1255897646],
  "id":  1
}
```

**Comment by niklasad1** [comment]
@rise0chen 

Can you elaborate why you mean?

By default one needs to pass the `"method": "unsubscribe-method-name"` and `"params": <sub_id>` for a subscription to be "unsubscribed" successfully by the server, exactly what your example shows.

**Comment by rise0chen** [comment]
I want to unsubscribe by one common method "unsubscribe_by_id".

**Comment by niklasad1** [comment]
It's already possible by using https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/trait.SubscriptionClientT.html#tymethod.subscribe_to_method but only supported by the client-side in jsonrpsee.

**Comment by lexnv** [comment]
From the perspective of subscribing using jsonrpse client (as Niklas mentioned), I believe the most straigh-forward way is using the [subscribe](https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/trait.SubscriptionClientT.html#tymethod.subscribe) method. Which will return a [Subscription](https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/struct.Subscription.html) object.
To then find the subscription ID, you'd need to call [Subscription::kind](https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/struct.Subscription.html#method.kind). 
To get the next item from the subscription, you'd need to call [Subscription::next](https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/struct.Subscription.html#method.next).
And from this point, the most straight-forward way to unsubscribe a client would be to call [Subscription::unsubscribe](https://docs.rs/jsonrpsee-core/0.21.0/jsonrpsee_core/client/struct.Subscription.html#method.unsubscribe).

Since we are following pubsub, you'd need to adjust the `Subscription::unsubscribe` method to not include the method name in the RPC request. Similarly, while creating the subscription, you'd need to modify the API to omit the `unsubscribe_method` name.

On the server side, you'd need to modify the mappings of subscriptions to identify them easily by the subscription ID (remove the `unsubscribe_method`).

Since the jsonrpsee follows pubsub, it might take some adjustments to achieve this, however I believe it's possible. This code would exist probably on a fork, which would need to be maintained.

**Comment by niklasad1** [comment]
What I'm trying to say is that one could add some code on-top of the subscription in the jsonrpsee server to support such thing without "forking" but the "client subscription" won't work of course instead one would do a "regular method call" to "unsubscribe_hello" without params and then all subscriptions will be closed.

```rust
async fn run_server() -> anyhow::Result<SocketAddr> {
    use tokio::sync::Mutex as AsyncMutex;

    let server = Server::builder().build("127.0.0.1:0").await?;
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel();

    struct Unsubscribe {
        closed: tokio::sync::mpsc::UnboundedSender<()>,
        unsubscribe_called: AsyncMutex<Option<tokio::sync::mpsc::UnboundedReceiver<()>>>,
    }

    impl Unsubscribe {
        async fn closed(&self) {
            self.closed.closed().await
        }
    }

    let mut module = RpcModule::new(Unsubscribe {
        closed: tx,
        unsubscribe_called: Some(rx),
    });

    module
        .register_subscription(
            "subscribe_hello",
            "s_hello",
            "__do_not_use",
            |_, pending, ctx| async move {
                let sub = pending.accept().await.unwrap();

                loop {
                    tokio::select! {
                        _ = tokio::time::sleep(Duration::from_millis(10)) => {
                            sub.send("Foo".into()).await.unwrap();
                        }
                        _ = ctx.closed() => {
                            break;
                        }
                    }
                }
            },
        )
        .unwrap();

    module
        .register_async_method("unsubscribe_hello", |_, mut ctx| async move {
            let rx = ctx.unsubscribe_called.lock().await.take();
            // When this is called, all subscriptions are closed.
            drop(rx);
            ()
        })
        .unwrap();

    let addr = server.local_addr()?;
    let handle = server.start(module);

    // In this example we don't care about doing shutdown so let's it run forever.
    // You may use the `ServerHandle` to shut it down or manage it yourself.
    tokio::spawn(handle.stopped());

    Ok(addr)
}

```

**Comment by niklasad1** [comment]
To conclude this is nothing we will support in jsonrpsee but possible to do if one wants to do it with some custom logic for it.

**Comment by rise0chen** [comment]
Thanks, I think I can solve it.
I want to save https://docs.rs/jsonrpsee/0.21.0/jsonrpsee/struct.SubscriptionSink.html to a HashMap, and search it by subscription_id, then call close().
