### ISSUE TITLE
WebSocket server-side upgrades

### ISSUE THREAD

**Issue by jtcoolen** [paritytech/jsonrpsee#1286]
Hello,

I was trying to replicate your code sample: https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/jsonrpsee_server_low_level_api.rs#L251 and was wondering how to obtain the WebSocket like in https://docs.rs/fastwebsockets/latest/fastwebsockets/#http-upgrades. The documentation of `ws::connect` tells that the WebSocket connection will held in another task but it is not clear to me how to use this connection to call a RPC.

Thanks in advance for your help!

**Comment by niklasad1** [comment]
Hey @jtcoolen 

It's similar to https://docs.rs/fastwebsockets/latest/fastwebsockets/#http-upgrades but our API is slightly more complicated.

`ws::connect`: does the http upgrade and returns whether WebSocket upgrade handshake was completed successfully or not and because we are tied to hyper the response must be sent to complete the request.

You can't really do anything with connection future, you should just spawn it if you want the server to running.
Thus, the typical use-case in mind is to drop the `conn_fut` if a peer is misbehaving in some manner.

The equivalent code is:

```rust
 let http_response = match ws::connect(req, server_cfg, methods, conn, rpc_middleware).await {
    Ok((rp, conn_fut)) => {
        // Run the WebSocket connection until completion....
        // i.e, respond the JSON-RPC calls
        tokio::spawn(conn_fut);
        rp
    }
    Err(rp) => rp,
  };

  // Complete HTTP handshake
  return http_response;
```

**Comment by jtcoolen** [comment]
Thanks @niklasad1,

Many thanks for your prompt response and explanation. Looking at the code a little bit, could we ensure that `ws::connect`, besides spawning a background task to handle the connection (https://github.com/paritytech/jsonrpsee/blob/master/server/src/transport/ws.rs#L468), returns the sender and receiver (https://github.com/paritytech/jsonrpsee/blob/master/server/src/transport/ws.rs#L454) so that they can be passed to `WSBuilder::build_with_transport` https://github.com/paritytech/jsonrpsee/blob/master/client/ws-client/src/lib.rs#L237C9-L237C29 to build a client to send RPCs?

**Comment by niklasad1** [comment]
@jtcoolen 

I don't understand what you want to do, you can't use the sender/receiver from there because it's owned by server and needed to drive the connection.  You really need to connect to the server via the server's URL.

Can provide example code what you want to do that would help us to understand what's the issue is (guessing that you want some custom transport and build a RPC client from that)

**Comment by jtcoolen** [comment]
Hello @niklasad1 
Yes the idea is to do something analogous to https://docs.rs/fastwebsockets/latest/fastwebsockets/#http-upgrades where a server can push messages to a client once the HTTP request is upgraded to a WebSocket connection.

**Comment by niklasad1** [comment]
Ok, it's not possible to push message to the client after HTTP handshake is completed with this API.
It will just start up a JSON-RPC WebSocket server with the configuration that you enable on it and handle messages from the client when `hyper::make_service_fn` returns. 

This, low-level API is essentially just an easy way for users to terminate the connection for custom use-cases.

Thus, what you want is not supported and we have no plans to support it but you could write your own logic similar to `ws::connect` by using any websocket library or whatever transport you want but utilize the jsonrpsee::RpcService to handle JSON-RPC specific calls.

**Comment by jtcoolen** [comment]
Thanks for the piece of advice!
