### ISSUE TITLE
how to disable certificate verification in jsonrpsee_http_client

### ISSUE THREAD

**Issue by YusongWang** [paritytech/jsonrpsee#1336]
```shell
HTTP error: error trying to connect: invalid peer certificate: UnknownIssuer
```

Does anyone know how to disable cert verify?

or did somebody fix the in-own repo?

**Comment by niklasad1** [comment]
Hey @YusongWang 

It's not possible to disable cert verification in jsonrpsee http client because it's using hyper-rustls which doesn't expose that.

I had a quick look and [rustls](https://github.com/rustls/rustls/issues/578) does allow it behind a feature flag `dangerous_configuration` but nothing that we plan to support in jsonrpsee.

Is it a self-signed certificate or what are you trying to do?

**Comment by YusongWang** [comment]
Yeah, I know the risk. and I do need this future.

thanks anyway.
close.

**Comment by niklasad1** [comment]
Ok, but if you are down to add support for a custom certificate store we could support it.

Basically we would need our CertificateStore to be like:


```rust
enum CertificaStore {
  Native,
  WebPki
  /// Here you could implement your own cert verifier
  Custom(Arc<dyn rustls::client::danger::ServerCertVerifier>)
}
```

**Comment by YusongWang** [comment]
> Ok, but if you are down to add support for a custom certificate store we could support it.
> 
> Basically we would need our CertificateStore to be like:
> 
> ```rust
> enum CertificateStore {
>   Native,
>   WebPki
>   /// Here you could implement your own cert verifier
>   Custom(Arc<dyn rustls::client::danger::ServerCertVerifier>)
> }
> ```

Thanks for the help,  I can not stuck too long for the issues.
