### ISSUE TITLE
Is there a way to close the subscription from the server?

### ISSUE THREAD

**Issue by yaziciahmet** [paritytech/jsonrpsee#1427]
My confusion is really simple. I have a usecase where it is best to close the subscription or the connection from the server-side. Is this achievable, if so how?

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @yaziciahmet

**Comment by niklasad1** [comment]
Hey @yaziciahmet 

I don't understand whether you want to close the just subscription or the entire connection.

1. Closing the subscription is trivial just return early from your subscription callback but you may want to send a special message before do so because the client will never know.  See https://github.com/paritytech/jsonrpsee/discussions/1223 for further information.
2. Closing the connection is possible but quite complicated to implement where you have to use [the low-level server API](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/jsonrpsee_server_low_level_api.rs) via middleware/extensions accessible in subscription callback to indicate to close down the connection.

**Comment by yaziciahmet** [comment]
Hey @niklasad1

I believe what I want is the ability to close the connection. It looks quite complicated to do. Is it planned anytime soon to add some sort of easier access to underlying connection, or maybe just a close functionality can be propagated down somehwo?

**Comment by niklasad1** [comment]
I prefer not add such thing into the subscription itself but perhaps we could add some builtin middleware to simplify it.
I have to double-check myself whether it's possible to implement...

**Comment by yaziciahmet** [comment]
Maybe return a tuple from `pending.accept()`? Subscription itself and a close callback?
