### ISSUE TITLE
Unparseable notification

### ISSUE THREAD

**Issue by Jomik** [paritytech/jsonrpsee#1435]
I am getting this message, which I _do not_ understand.
```log
Unparseable message: {"jsonrpc":"2.0","method":"notify_klippy_disconnected"}
```
Why is this not parseable ? It is json and it has both the `jsonrpc` field and the `method`?
There is a few like this, but also a bunch that are working.

```toml
jsonrpsee = { version = "0.24.1", features = [
  "tokio",
  "ws-client",
  "jsonrpsee-core",
] }
```

**Comment by niklasad1** [comment]
You are right, it's a bug, [the notification](https://github.com/paritytech/jsonrpsee/blob/master/types/src/request.rs#L109) requires the params field which may be omitted.

The fix is either to [to make params an Option in the Notification type](https://github.com/paritytech/jsonrpsee/blob/master/types/src/request.rs#L109) or change [T to Option<JsonValue>](https://github.com/paritytech/jsonrpsee/blob/master/core/src/client/async_client/mod.rs#L731)

**Comment by Jomik** [comment]
I thought so! How do I make that change? I don't see the `Notification` type used anywhere in my code, so it seems like an internal thing? This seems to be the line that fails https://github.com/paritytech/jsonrpsee/blob/bc7f8ebc5b056e007c3abdcf7d7af17cec7587df/core/src/client/async_client/mod.rs#L731

**Comment by niklasad1** [comment]
Yepp, it's an internal thing that we must change :(

**Comment by Jomik** [comment]
That would be absolutely amazing 👍
