### ISSUE TITLE
[clients]: new type abstraction for `atomic request IDs`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#290]
We are using `AtomicU64` in the clients to get new `request ID(s)` and those are exposed as raw `AtomicU64`. 
There is nothing really that prevents `read/store` the values with inproper ordering  thus we have made them explicit `SeqCst` to be on the safe side.

It would be better to wrap those `AtomicU64` in a `new type` such as `AtomicCounter` to prevent misuse of them and I think that's the only proper use-case for `Ordering::Relaxed`

Also, see the discussion in #289 for further information

**Comment by jsdw** [comment]
I def have no issue wrapping the type, but if `Relaxed::Ordering` is sufficient (because we aren't trying to assume anything about the ordering of surrounding operations when we modify this atomic), then I don't really see what can go wrong (every other ordering you could use is stronger than relaxed anyway, so there's nothing you can really do to mess it up is there?)  :)

**Comment by dvdplm** [comment]
> I read some C++ guidelines on this and they recommend for Ordering::Relaxed is to wrap it in new type such makes only possible to do add and nothing else. **Then the rest of the code doesn't have to care about it.**

I think the key point here is this: relieving readers from even having to think about ordering, a notoriously thorny topic. :)

**Comment by niklasad1** [comment]
Yeah, the idea is to have an wrapper on top of `AtomicUInt`
Basically it only allows the following:

```
struct AtomicCounter(AtomicU64);

impl AtomicCounter {
   /// Increment the counter and return the previous value.
    pub fn inc(&self) -> u64 {
      self.0.fetch_add(1, Ordering::Relaxed)
    }
}
```

Thus, should not be possible to misuse and do weird stuff. Just increment the value :)
