### ISSUE TITLE
Trait object for Client

### ISSUE THREAD

**Issue by gbaranski** [paritytech/jsonrpsee#474]
Hi, I'd like to use something like `Box<dyn Client>` and allow `Client` to be either `HttpClient` or `WsClient`, it's currently not possible with `jsonrpsee::types::traits::Client` because of `request` and `batch_request` have generic params. What do you think about that?

**Comment by niklasad1** [comment]
ah right, we have discussed this briefly and the main reason for the client traits is that those introduced in order for the `derive macros/proc macro API` to work.

we had the assumption that users should probably pick either `HTTP` or `WS` at compile-time but maybe you could elaborate your usecase? 

In addition, maybe we could introduce an extension trait with `serde_json::Value` instead of the generics

//cc @maciejhirsz @dvdplm thoughts?

**Comment by gbaranski** [comment]
> we had the assumption that users should probably pick either `HTTP` or `WS` at compile-time but maybe you could elaborate your usecase?

I want users to choose URL of RPC server, and the URL has can either start with http:// or ws://, so if users uses the HTTP prefix, I'd like to create HttpClient, if it uses WS prefix, I'd like to create WsClient, however i think it could be solved by making an enum and manually implementing Client trait on it.

**Comment by dvdplm** [comment]
Good question! 
Our reasoning was that trying to pretend that `http` and `ws` are "just" different transports, but able to do the same thing ends up causing more problems than it solves. At the end of the day, the reasoning went, users tend to predominantly use either the one or the other; few use both interchangeably. 
This gives us some freedom to let the APIs diverge a bit and evolve independently.

It sounds like it could be worked around fairly easily in user code; if you do run into a situation where it becomes really awkward and difficult to use, let us know and we can have a re-think?

**Comment by hexcowboy** [comment]
I'm working on a project where the user supplies a list of RPCs to connect to, either WS or HTTP. It is very awkward since not even `ClientT` can be made into a dynamic object due to generic parameters.

It would be nice to have a trait that at least has majority overlapping functions, so it can be used interchangeably for runtime types.
