### ISSUE TITLE
Support for customized logging

### ISSUE THREAD

**Issue by crystalin** [paritytech/jsonrpsee#487]
Ideally, the library should allow the user to control how the logs are produced.
Here is the requirements we believe are needed for our parachain node:
- Support to log the request, including its payload*
- Support to log the response, including its payload* and the timing
- *Payload could be filtered (to include some fields, or based on the method used). The possibility to reduce the the content of the fields in the payout automatically (like an array of 1000 items displaying only the first and last item).

**Comment by librelois** [comment]
One possibility proposed by @dvdplm would be to integrate `sc_tracing` and allow users to inject their own `tracing-subscriber`.

**Comment by niklasad1** [comment]
This is partly fixed by #722

It adds a tracing span per `method name` with a limit just to truncate logs bigger than `n` characters.
What's is nice is that you can subscribe to just a method name that you are interested in  instead of doing it globally with middleware (unless you want to recompile and have some filter).


But we'll add more details in the middleware too soon so we can pick either because `tracing` is a bit less flexible for users as the logging output is simply truncated.

**Comment by niklasad1** [comment]
Closed by #793 

jsonrpsee has both "tracing spans" and middleware for you customize your logging.
