### ISSUE TITLE
Feature request: expose an access to http server handle

### ISSUE THREAD

**Issue by slumber** [paritytech/jsonrpsee#547]
Call to [`HttpServer::start`](https://docs.rs/jsonrpsee-http-server/0.4.1/jsonrpsee_http_server/struct.HttpServer.html#method.start) consumes the server, spawns a task and gives you a [`StopHandle`](https://docs.rs/jsonrpsee-http-server/0.4.1/jsonrpsee_http_server/struct.HttpStopHandle.html).
As far as I see it, there's no easy way to simply "run forever"? `tokio` join handle is private, `StopHandle` doesn't implement `Future`, probably I miss something, but this looks a little bit inconvenient.

I'd propose to rename `StopHandle` into `ServerHandle` and make it awaitable the same way it works in actix:
[`HttpServer::run`](https://docs.rs/actix-web/3.3.2/actix_web/struct.HttpServer.html#method.run) returns [`Server`](https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.Server.html) which can be used to [`stop`](https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.Server.html#method.stop) the server or can be awaited on to run the application forever (since it [implements](https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.Server.html#impl-Future) `Future`).

**Comment by niklasad1** [comment]
> As far as I see it, there's no easy way to simply "run forever"?

Ok, I see you make a good point. Right, you need to keep the stop handle somewhere otherwise it will shutdown when it's dropped that might be annoying yes.

> tokio join handle is private, StopHandle doesn't implement Future, probably I miss something, but this looks a little bit inconvenient.

I don't get what you mean by private you can just await on the `tokio::JoinHandle` because it impls `Future`, such as:

```rust
if let Ok(stop) = server.stop() {
  stop.await.unwrap();
}
```

> I'd propose to rename StopHandle into ServerHandle and make it awaitable the same way it works in actix:
HttpServer::run returns Server which can be used to stop the server or can be awaited on to run the application forever (since it implements Future).

Sounds like a good idea to me, it was done this to have a "uniform API" with WsServer but perhaps we can change both.
What do you think @maciejhirsz?

**Comment by slumber** [comment]
> I don't get what you mean by private you can just await on the `tokio::JoinHandle` because it impls `Future`, such as:
> 
> ```rust
> if let Ok(stop) = server.stop() {
>   stop.await.unwrap();
> }
> ```
> 
I mean the underlying join handle could be used for running the server forever, but it's private (which totally makes sense). In your example, at this point handle is only returned after sending the shutdown signal.
> Sounds like a good idea to me, it was done this to have a "uniform API" with WsServer but perhaps we can change both. What do you think @maciejhirsz?

I could submit a PR if the proposal gets approved
