### ISSUE TITLE
Make it trivial to convert a `RpcModule<Something>` to `RpcModule<()>`

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#558]
Atm users sometimes have to do this to get an `RpcModule` with a void context, `()`:

```rust
		let rpc_api = SomeRpcThing::new(ctx).into_rpc();
		let mut module = RpcModule::new(());
		module.merge(rpc_api).expect("only one module; qed");
		Ok(module)
```

Add a QoL method to `RpcModule` that consumes `self` and returns a `RpcModule<()>`.

**Comment by maciejhirsz** [comment]
Instead of replacing the context, we could also downgrade the module to `Methods` (maybe rename `Methods` to `RpcMethods` to reduce the gravity of the name first?). That can already be done with just `.into()`.

`RpcModule::merge` takes `Into<Methods>` as an argument, so just having bare `Methods` is enough as long as no new methods are added post-factum.
