### ISSUE TITLE
[ws-client] Make wasm compatible

### ISSUE THREAD

**Issue by athei** [paritytech/jsonrpsee#606]
There is #227 which covers making the http client wasm compatible. However, I think the ws client is much more important because it is the only one allowing subscriptions. It would allow for creating web frontends written in Rust through `subxt`.

With wasm compatible I mean "runs in a browser". This means making use of `web-sys` to interact with the browser.

**Comment by niklasad1** [comment]
> However, I think the ws client is much more important because it is the only one allowing subscription

yeah, indeed.

It's been a while since I looked at the https://github.com/najamelan/ws_stream_wasm but it won't because the `"async/ws" client` assumes it assumes that it can be split into a sender and receiver because we using them in different tasks.

However, https://github.com/nash-io/nash-ws looks quite promising. I think it should be straight-forward to port over.

**Comment by athei** [comment]
Maybe its worthwhile to use [`web-sys`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html) directly. This crate looks kind of abandoned.

**Comment by niklasad1** [comment]
Closed by #648
