### ISSUE TITLE
How to disable max_notifs_per_subscription threshold

### ISSUE THREAD

**Issue by gitmalong** [paritytech/jsonrpsee#666]
```rust
    let client = WsClientBuilder::default()
                .max_concurrent_requests(10_000)
                .build(&url)
                .await
                .unwrap();
```

Does `max_concurrent_requests` limit the number of currently active subscriptions?

Could you please also clarify how I can disable the `max_notifs_per_subscription` limit? Does it limit the maximum number of messages the subscription can receive? What's the exact purpose of that?

**Comment by niklasad1** [comment]
> Does max_concurrent_requests limit the number of currently active subscriptions?

No, not exactly it works per `JSON-RPC call/notification` basis so after the `subscribe_call` is completed that limit is counter is decreased.

> Could you please also clarify how I can disable the max_notifs_per_subscription limit? Does it limit the maximum number of messages the subscription can receive? What's the exact purpose of that?

`max_notifs_per_subscription` configures how large the buffer for `mpsc channel` to store items that haven't been consumed yet, [see docs here](https://github.com/paritytech/jsonrpsee/blob/master/core/src/client/async_client/mod.rs#L93-#L101). Exactly how big it should be depends on your use-case and how "frequent" you `poll` `Subscription::next` i.e, how many items that can be `buffered`. 

You can't really disable it but you can set it to some big values such as `usize::MAX - 1`.

The purpose is that if you want to ensure your application only is using `bounded amount memory` and if that's exceeded the subscription is simply dropped because your application could not keep up with the server.

I see that the rustdocs doesn't document the code hidden behind feature flags, we should fix that.

**Comment by gitmalong** [comment]
Thanks for elaborating on that @niklasad1. I had overlooked that code comment.

**Comment by niklasad1** [comment]
If that's is not clear by the docs we should improve it, I would love PRs regarding the documentation :)
