### ISSUE TITLE
Clarify the client error situation

### ISSUE THREAD

**Issue by tomaka** [paritytech/jsonrpsee#67]
What happens when an error happens on the client side?
Everything in `Client` and `RawClient` regarding the behaviour after errors should be properly documented.

**Comment by tomaka** [comment]
Note: this issue was created at a time when the `TransportClient` was named `RawClient` and `RawClient` was named `Client`.

The questions in play here is: how do we indicate whether this is an error about a single request, or an error on the entire connection? Is the transport's state still valid after an error has been produced? Everything should be strongly typed and documented.

**Comment by tomaka** [comment]
Unfortunately there's a big design flaw in that there's no way to associate a request with a response in the `TransportClient`. That means that for example an HTTP client that opens one connection per request cannot report that a specific request resulted in a 4xx or 5xx error.

**Comment by niklasad1** [comment]
This is now fixed by having the following:
- `http`, the background thread is removed and we just return propogate the error to the user if that happens (it's "synchronous-like")
- `ws` when an error is received we terminate the connection and the client becomes useless, the error message is not great which could be improved but "hey you can read the logs" :roll_eyes: 

However, the documentation could be more explicit regarding this but closing anyway.
