### ISSUE TITLE
how can i read a middleware to verify request authentication

### ISSUE THREAD

**Issue by hunjixin** [paritytech/jsonrpsee#707]
what i want todo. is below
1. read http header and get authentication value
2. verfiy token and check api permission
3. if okay call method, if error respons no authentication

in current middleware, have no way to read header and abort request.

**Comment by dvdplm** [comment]
Hello! The `jsonrpsee` library is not intended to be a fully featured web server and does not provide user authentication. The best advice is to build out such extra features using a tool built for that purpose yourself so you get a solution that fits your needs and then use `jsonrpsee` to power the backend API.

**Comment by hunjixin** [comment]
yes jsonrpsee is not fully featured web server, but it should be a better rpc libirary, i think a more power middleware is indeed. for example in current implement , i see access control written in http server directly, but maybe a better way maybe implement in a middleware like webapi in c#,   when

**Comment by niklasad1** [comment]
@hunjixin 

Please see https://github.com/paritytech/jsonrpsee/issues/699

We have slightly changed our minds regarding this since we introduced the middleware for metrics so the idea is to extend to middleware such that you can access the `http headers` and build whatever you want on top of that.

Sound ok?
