### ISSUE TITLE
Strange method_call response

### ISSUE THREAD

**Issue by sander2** [paritytech/jsonrpsee#714]
One of our SubXt calls seems to have gotten stuck. After investigating the logs, I think this might be the cause: 

```
jsonrpsee_core::client::async_client: [backend]: recv subscription Notification { jsonrpc: TwoPointZero, method: "author_extrinsicUpdate", params: SubscriptionPayload { subscription: Str("3s8bKsA3IWgmGbyU"), result: String("ready") } }
jsonrpsee_core::client::async_client: [backend]: recv subscription Notification { jsonrpc: TwoPointZero, method: "author_extrinsicUpdate", params: SubscriptionPayload { subscription: Str("3s8bKsA3IWgmGbyU"), result: Object({"broadcast": Array([String("12D3KooWP5Ye7wZLtDvjb6qJnpGMVvH6kqFgWTkN3x1Z3SfScEUY"), String("12D3KooWRiX39ELHouAuHRjBTgT9312bmNikJw82vxHf614xzUb1")])}) } }
jsonrpsee_core::client::async_client: [backend]: recv method_call Response { jsonrpc: TwoPointZero, result: String("3s8bKsA3IWgmGbyU"), id: Number(2613) }
```

Note the method_call response. As far as I can tell, all other method call responses have a hex string as result (e.g., `0x1234...`), whereas this particular response contains the subscription id. Am I correct in assuming this is erroneous behavior that should not be happening, and that could possibly cause SubXt to get stuck? What could be causing this?

**Comment by niklasad1** [comment]
Hey @sander2, yes your understanding is correct.

You ran into https://github.com/paritytech/substrate/issues/10910 I guess, I hope this goes away once we move the jsonrpsee servers as well over there.

Basically, the server starting sending out subscription responses without propagating the subscriptionID first. So the actual subscription is not known when those messages appear so those are simply "ignored" by jsonrpsee because they don't belong to a "registered subscription"

It could in fact cause subxt/the subscription to not return anything if those two messages are not received properly in this case (I don't think no further notification is sent after "status": broadcast)
