### ISSUE TITLE
Request vs Call Error

### ISSUE THREAD

**Issue by gregdhill** [paritytech/jsonrpsee#715]
We currently have a workaround [implemented here](https://github.com/interlay/interbtc-clients/blob/919b54483b2574dce7b2894d0bdec512a89031eb/runtime/src/error.rs#L165-L185) to convert `Error::Request` into `Error::Call` but this shouldn't be necessary and it's not clear to me when these variants are produced. We can reliably reproduce (and test) the latter but I would like to catch all possible avenues of regression.

**Comment by niklasad1** [comment]
We didn't manage the unify `Error::Request` and `Error::Call` them because of lifetime issues w.r.t `serde_json::RawValue` but I missed that `RawValue` has `to_owned` to API so should be possible to remove `Error::Request`.

`Error::Request` is the same as `Error::Call` without lifetime stuff, borrows and so on.

**Comment by niklasad1** [comment]
Closed by #717
