### ISSUE TITLE
Batch Response being sorted by the request payload order

### ISSUE THREAD

**Issue by crystalin** [paritytech/jsonrpsee#830]
This is not a bug, but more to match other JSONRPC implementations.
We observed that request and response payload are in different order:
```
request:
[{"jsonrpc": "2.0", "id": 1, "method"....},
 {"jsonrpc": "2.0", "id": 2, "method"....},
 {"jsonrpc": "2.0", "id": 3, "method"....}]
 
 response:
 [{"id": 3, ...},
 {"id": 1, ....},
 {"id": 2, ....}]
 ```
 The response order is probably (I haven't looked) by order of execution, which is fine as the specs don't specify any order (https://www.jsonrpc.org/specification#batch), but is not matching what most of the other JSONRPC providers are doing.
 
 I'd suggest we return also the response payload in the same order. What do you think ?

**Comment by niklasad1** [comment]
IMHO it's more a client implementation bug because the client need to support unordered batch responses because of the spec but if all other implementations return `ordered batches` we could maybe do that same but it's more inefficient for the servers.

Further, the JSON-RPC spec relies on the client implementation to actually keep the order of the calls in the batch to get it back in order. We do that ourselves in the client implementation which is quite annoying but I guess "it could decrease some load on the servers to avoid sorting" and move that to the clients instead.

Sorting the batch response would be quite annoying currently as these methods get back the responses a finally formatted JSON strings and each call spawned independently on the executor.

Not sure if we could use `FuturesOrdered` or something instead.

//cc @jsdw @lexnv thoughts?

**Comment by jsdw** [comment]
The other thing the spec points out is that notifications can be part of a batch, and there would be no responses to those, so the client always has to be able to deal with things being potentially misaligned (ie call item at index 3 in the batch might not correspond to response item at index 3).

So ultiamtely, whatever we do w.r.t sorting or not, the user needs to untangle the response and match things up based on the IDs anyway, so I wonder whether there is really any benefit from trying to sort things? It may just give clients the false impression that they can match on index, and one day that might lead to something breaking quite badly.

**Comment by crystalin** [comment]
I agree with the 2nd point. Forcing clients to always process it correctly has probably a better impact long term.
However there are also cases where people are not using tools, like querying directly with `curl`. They should rely on the Id but it still makes it easier to read if ordered as expected.

Up to you to decide :)

**Comment by jsdw** [comment]
It feels like it'll probably be a small performance hit to do this for batch calls, and I suspect a slight increase in code compliexty, and so if clients need to take care to line these things up anyway then my vote would be not to worry about doing so here. I appreicate that it makes it slightly harder to line things up for debugging purposes though.

**Comment by jsdw** [comment]
We had a chat and decided to close this for now. That said, we do accept contributions, so if you'd like to propose a PR with a change in (probably somehting involving eg `FuturesOrdered`) we'd consider it!
