### ISSUE TITLE
Assert_eq doesn't work for jsonrpsee_types::error

### ISSUE THREAD

**Issue by nakul1010** [paritytech/jsonrpsee#832]
The partial Eq and Eq traits are missing for the Error type due to which assert_eq is not working which is extensively used to write test cases.

**Comment by niklasad1** [comment]
hey,

which type are you referring to is it [jsonrpsee::Error](https://docs.rs/jsonrpsee-core/0.15.1/jsonrpsee_core/error/enum.Error.html), [jsonrpsee_types::ErrorObject](https://docs.rs/jsonrpsee-types/0.15.1/jsonrpsee_types/error/struct.ErrorObject.html) or some other type you are referring to?

The reason is that some trait bounds can't be satisfied because some error types are generic i.e, `T: StdError + Send + Sync`.

I reckon that that might be annoying but you can convert the error to a String and compare them or do `assert_matches`

**Comment by nakul1010** [comment]
hey, 
I am using jsonrpsee_core::error.

**Comment by jsdw** [comment]
Going to close this for now; one workaround might be to stringify errors and compare those? (eg `assert_eq!(my_error.to_string(), Error::Foo.to_string())`
