### ISSUE TITLE
Sync mode

### ISSUE THREAD

**Issue by jb-alvarado** [paritytech/jsonrpsee#833]
Hello,
I wanted to ask if there is a sync mode, without the use of tokios async/await?

I know all world moves to async, but sometimes is just not needed :-).

**Comment by niklasad1** [comment]
Yes, we got 

[RpcModule::register_method](https://docs.rs/jsonrpsee-core/0.15.0/jsonrpsee_core/server/rpc_module/struct.RpcModule.html#method.register_method) and [RpcModule::register_blocking_method](https://docs.rs/jsonrpsee-core/0.15.0/jsonrpsee_core/server/rpc_module/struct.RpcModule.html#method.register_blocking_method) which are "sync"

but the servers themselves requires tokio to be spawned.

Thus, you need spawn the servers on tokio but then it's possible to define async, sync or blocking methods..
Not sure if you want get rid of the async stuff entirely but that won't work currently.

**Comment by jb-alvarado** [comment]
Thank you Niklas, for clarification! Yes I wanted to get rid of async stuff (in server mode) entirely. But I understand, when you can not provide a solution for every situation. At the moment I'm fine with your older *[jsonrpc](https://github.com/paritytech/jsonrpc)*, I'm only try to plan a bit for the future.

**Comment by niklasad1** [comment]
I was wrong you don't need tokio but https://docs.rs/jsonrpsee-ws-server/0.15.0/jsonrpsee_ws_server/struct.WsServerBuilder.html#method.build & https://docs.rs/jsonrpsee-http-server/0.15.0/jsonrpsee_http_server/struct.HttpServerBuilder.html#method.build are async so you need to workaround that with `futures::future::block_on` or something.

Maybe we could provide a blocking variant of that method.

That's it otherwise it should work in `sync/blocking mode`

**Comment by jb-alvarado** [comment]
That is a good hint! I will see if I can use this workaround. And if you could provide a blocking variant to, would be great!
