### ISSUE TITLE
Wasm client have no module

### ISSUE THREAD

**Issue by mustafasegf** [paritytech/jsonrpsee#858]
I can't use `use jsonrpsee_wasm_client::WasmClientBuilder;` because it's not a module. I can't figure out how to use the wasm_client because of this.

**Comment by niklasad1** [comment]
Hey.

Can you elaborate how you are trying to use it?

Because of [this](https://github.com/paritytech/jsonrpsee/blob/master/client/wasm-client/src/lib.rs#L28) it is only available when are compiling as `cargo build --target wasm32-unknown-unknown` or try with `wasm-pack`

Thus, it won't work if you try to build with your default target on your machine.
Perhaps, we could provide a better compile error for this but it should work for `--target wasm32-unknown-unknown` AFAIU.

**Comment by mustafasegf** [comment]
so i use `wasm-pack new` and add wasm-client with `cargo add jsonrpsee --features wasm-client`

but I cant import the `WasmClientBuilder`
I import it using `use jsonrpsee::wasm_client::WasmClientBuilder;`

the error says
`1. unresolved import `jsonrpsee::wasm_client::WasmClientBuilder` no `WasmClientBuilder` in the root`

**Comment by niklasad1** [comment]
Hey again,

I can't reproduce this, are you sure that you are using `cargo build --target wasm32-unknown-unknown` or `wasm-pack test --headless --firefox`?

Which version of jsonrpsee are you using?

Can you please run `cargo build --target wasm32-unknown-unknown --verbose` and paste the output below?

**Comment by mustafasegf** [comment]
ok so I think the problem is on my rust analyzer, I can compile it without issue. Thanks for answering.

**Comment by niklasad1** [comment]
ok, we can try to get rid of those `target_arch = wasm32` conditional compilation to improve that

**Comment by mustafasegf** [comment]
after adding `target = "wasm32-unknown-unknown"` on my `.cargo/config.toml` it fixed the rust analyzer issues. Maybe you can add up that info somewhere.
