### ISSUE TITLE
Change ParamsSer::Map inner type

### ISSUE THREAD

**Issue by llacqie** [paritytech/jsonrpsee#902]
Change ParamsSer::Map inner type from BTreeMap<&'a str, JsonValue> to JsonValue.

Because with current type we can't just make a struct with params like:
```
#[skip_serializing_none]
#[derive(Debug, Serialize)]
pub struct SetDaemon {
	pub address: Option<String>,
	pub trusted: Option<bool>,
	pub ssl_support: Option<SecureSocketsLayerSupport>,
	pub ssl_private_key_path: Option<String>,
	pub ssl_certificate_path: Option<String>,
	pub ssl_ca_file: Option<String>,
	pub ssl_allowed_fingerprints: Option<Vec<String>>,
	pub ssl_allow_any_cert: Option<bool>,
}
```
and then pass instance of it as params:
```
pub async fn set_daemon(&self, params: params::SetDaemon) -> Result<()> {
	self.http_client
		.request("set_daemon", Some(ParamsSer::Map(params)))
		.await
}
```
PS: I can't use ParamsSer::Array because API that I want to use(monero-wallet-rpc API) requires params to be:
`
{
...
	params: {...},
...
}
`
and not:
`
{
...
	params: [{...}],
...
}
`

**Comment by niklasad1** [comment]
`ParamsSer::Map` has already been removed on master but it's not released yet, there is another type [ObjectParams](https://github.com/paritytech/jsonrpsee/blob/master/core/src/params.rs#L145) but that will run into the same issue.

The reason why we can't use `JsonValue` directly is because it doesn't ensure that it actually deserializes to a JSON object.

You can impl [ToRpcParams](https://github.com/paritytech/jsonrpsee/blob/master/core/src/traits.rs#L81-#L84) for you type instead.

**Comment by llacqie** [comment]
> `ParamsSer::Map` has already been removed on master but it's not released yet, there is another type [ObjectParams](https://github.com/paritytech/jsonrpsee/blob/master/core/src/params.rs#L145) but that will run into the same issue.
> 
> The reason why we can't use `JsonValue` directly is because it doesn't ensure that it actually deserializes to a JSON object/map.
> 
> You can impl [ToRpcParams](https://github.com/paritytech/jsonrpsee/blob/master/core/src/traits.rs#L81-#L84) for you type instead.

Okay, but as I understand it, it won't work on the release version, right? If so, when is the next release?

**Comment by niklasad1** [comment]
Yeah, or you could patch the version on crates.io as well with master but not recommended. 

"Soon" should be released in a week or two.
