### ISSUE TITLE
[server] Does the server side support several notification methods to be called in one registered RPC method?

### ISSUE THREAD

**Issue by harlanc** [paritytech/jsonrpsee#916]
Just like the following usages from a golang jsonrpc library:

1、Register the [join](https://github.com/pion/ion-sfu/blob/7b6cc7bf6ac2aa4675b0ffcbbd631c791d7122c6/cmd/signal/json-rpc/server/server.go#L52) method on the server side:

2、And in the registered "join" method, two notification methods ([offer](https://github.com/pion/ion-sfu/blob/7b6cc7bf6ac2aa4675b0ffcbbd631c791d7122c6/cmd/signal/json-rpc/server/server.go#L62) and [trickle](https://github.com/pion/ion-sfu/blob/7b6cc7bf6ac2aa4675b0ffcbbd631c791d7122c6/cmd/signal/json-rpc/server/server.go#L68)) are called.

By using which methods from jsonrpsee can  achieve this goal? Thanks.

**Comment by niklasad1** [comment]
hey @harlanc 

It's not possible currently mainly because for two reasons:
1. `register_methods` only supports return a response from the callback as `JSON-RPC response object` and has no option the  send out notifications. Could be possible add another version of that with possibility to send notification a part of the callback.
2. There is no API for sending out server-side notifications.  We/parity doesn't need it because we rely on ethereum pubsub subscription stuff instead.

Can you elaborate how one would use this API?

1. The client call `"method = join"`
2. The server sends out notifications "periodically/at some event" to `offer` and `trickle`?

IIRC, we added support for the clients to subscribe to notifications based on name as well.

**Comment by harlanc** [comment]
hi @niklasad1 

Thanks for you explanation.

Can you elaborate how one would use this API?

The client call "method = join"
The server sends out notifications "periodically/at some event" to offer and trickle?

---------
Yes, you are right.
Web client will call the "join" RPC method of server to join a room session, and server will notify the web client using offer and trickle when some event happens.


There is no API for sending out server-side notifications. We/parity doesn't need it because we rely on ethereum pubsub subscription stuff instead.
--------

You mean that using "register_subscription" can meet my needs? But I found that the register_subscription method can only support one notification method??

And we use web client to communicate with server, if the javascript/typescript/rust APIs strictly adhere to the json RTC standards, I think they can communicate successfully.

**Comment by harlanc** [comment]
thanks , I wrote a simple json-rpc2 library myself..
