### ISSUE TITLE
Access to RPC handler/jsonrpsee::TowerService

### ISSUE THREAD

**Issue by ultd** [paritytech/jsonrpsee#918]
Can we make the [`TowerService`](https://github.com/paritytech/jsonrpsee/blob/990c120dc6f72eace65be4a1976b82cfad055a75/server/src/server.rs#L582) accessible externally so one can implement their own `hyper` based server with custom routing, authentication, middlewares, etc.?

Effectively making it so that it can be used anywhere a `Service<Request<ReqBody>>` is accepted? Happy to contribute if any desire for this from others.

**Comment by ultd** [comment]
https://github.com/paritytech/jsonrpsee/blob/990c120dc6f72eace65be4a1976b82cfad055a75/server/src/server.rs#L582

**Comment by niklasad1** [comment]
Hey @ultd 

The idea is that you can provide your own middleware in [ServerBuilder::set_middleware](https://github.com/paritytech/jsonrpsee/blob/master/server/src/server.rs#L446) but you have to implement a custom TowerService for that. 

We have [an example proxied for get request middleware here](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http_proxy_middleware.rs) and [example implementation of TowerService](https://github.com/paritytech/jsonrpsee/blob/master/server/src/middleware/proxy_get_request.rs)

The reason is that jsonrpsee need to have access to underlying `hyper service fn` to verify that HTTP request, maybe upgrade it to WebSocket connection and to call actual RPC method.

Without that it's not possible then your are likely better to use your own hyper server and use `core server module`, so that's why it's not possible.

/cc @lexnv @jsdw any additional comments/clarification or did I get anything wrong? :)

**Comment by ultd** [comment]
> The idea is that you can provide your own middleware in [ServerBuilder::set_middleware](https://github.com/paritytech/jsonrpsee/blob/master/server/src/server.rs#L446) but you have to implement a custom TowerService for that.

I think it would be better to allow users to "mount" the service wherever they need it to be as opposed to being limited to running an HTTP server via the `ServerBuilder`.

> The reason is that jsonrpsee need to have access to underlying hyper service fn to get access to the HTTP request, maybe upgrade it to WebSocket connection and to call the actual RPC method.
>
> Without that it's not possible then your are likely better to use your own hyper server and use core server module, so that's why it's not possible.

The `TowerService` implements the `Service` trait which in the `call` method, `request: Request<Body>` arg has access to underlying `http` request. This is where the actual upgrades and method calls are performed so it should definitely be possible.

**Comment by niklasad1** [comment]
> The TowerService implements the Service trait which in the call method, request: Request<Body> arg has access to underlying http request. This is where the actual upgrades and method calls are performed so it should definitely be possible

Right,  I guess if it could be possible to have extract `the jsonrpsee TowerService` from `Server/ServerBuilder` then it should work but it has some specific stuff to our `fn start/event loop to handle connections and so on which may be annoying to have.

If you can figure out a proper API for it then it should be nice to have.

**Comment by jscheid** [comment]
I'm also interested in this. My use case is to run the server on a non-TCP socket.

**Comment by jscheid** [comment]
I might be missing something but wouldn't manually instantiating `ServiceData` do the trick? It's not possible currently because it's `pub(crate)` but if it was public, what else would we need?

**Comment by niklasad1** [comment]
Closing, created a new issue #1016
