### ISSUE TITLE
How to create tcp server?

### ISSUE THREAD

**Issue by rise0chen** [paritytech/jsonrpsee#937]
like [jsonrpc-tcp-server](https://lib.rs/crates/jsonrpc-tcp-server)

**Comment by niklasad1** [comment]
Hey @rise0chen 

jsonrpsee server doesn't support `tcp transport` only `http and WS`

**Comment by niklasad1** [comment]
> Are there any plans for the future
> ?

No, since "we/parity" have no internal need for this feature, we'd happily would accept external contributions. 
You can have a look at the discussion #5 around IPC support the same applies to TCP transport.

Thus, closing this issue because it is not something we working on to support any time soon.
