### ISSUE TITLE
Logger/middleware for rpc client?

### ISSUE THREAD

**Issue by allquixotic** [paritytech/jsonrpsee#972]
I have a client class generated using the rpc macro. How can I use logger/middleware with this to see the contents of all HTTP responses, even those from failed requests that generated an Error?

**Comment by lexnv** [comment]
Hey!

IIRC the client should log the requests and responses.
Would adding the `RUST_LOG=trace` when starting your program provide enough details here?

**Comment by niklasad1** [comment]
Yes, as @lexnv `RUST_LOG=trace` and make sure that you use the `tracing_subscriber` because `env_logger` and similar doesn't output the tracing output.

You could even subscribe to certain `rpc methods` with the tracing stuff, [example here](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http.rs#L37-#L39)

Further, we have no middleware for the clients but I think it should be rather trivial to add `tower` in the clients as well.

**Comment by allquixotic** [comment]
Thanks for the help.

However, I'm still not seeing the HTTP response body. Here is my code and the output: https://gist.github.com/allquixotic/f1b02d7e674cdd4abd72b46cb9ff2d57

**Comment by niklasad1** [comment]
jsonrpsee isn't logging the HTTP request and response so that's the reason why you can't find it.
We are logging jsonrpc related stuff but we could add it though I reckon it could be useful when debugging stuff...

I did re-run your app with logging the request and the URI looks good:

```
2023-01-18T15:58:32.379730Z  INFO method_call{method="User.login"}: jsonrpsee_http_client::transport: req: Builder { inner: Ok(Parts { method: POST, uri: https://www.enjin.com:443/api/v1/api.php, version: HTTP/1.1, headers: {"content-type": "application/json", "accept": "application/json"} }) }
```

I have no idea why the HTTP request fails but I guess bad user name/password (the HTTP library we use doesn't return response body on failures)

**Comment by allquixotic** [comment]
> the HTTP library we use doesn't return response body on failures

That's unfortunate. Since I can't figure out what error the server is giving me, I'm not sure how to proceed. I'm certain my credentials are correct, and the request looks good, so I need to be able to fully see the HTTP layer of the stack. 

I'm going to have to put my use of Rust on hold due to this problem and probably switch my project over to Kotlin where better debugging info is available. Thanks for the help.

**Comment by allquixotic** [comment]
Also, independent of you guys doing any work on jsonrpsee to make this better, I added HTTP proxy support to jsonrpsee. See: https://github.com/paritytech/jsonrpsee/pull/975

This helps me debug the raw payload :)

**Comment by allquixotic** [comment]
Now I have the raw payload, working sourcecode in Python, and broken sourcecode in Rust, and I still can't figure out what jsonrpsee is doing "wrong" to cause the Enjin server to throw an error. Anyone have any idea from this? https://gist.github.com/allquixotic/34c36951c4ba19dd47882e77a0f06d23

**Comment by allquixotic** [comment]
This fixed my jsonrpsee usage:

```
headers.insert("Accept", "*/*".parse().unwrap());
headers.insert("User-Agent", "anything".parse().unwrap());
```

**Comment by niklasad1** [comment]
Closing this because middleware has been added to the HTTP client in #981.

I have looked at the websocket client as well but looks tricky as we have no access to that in the websocket transport library.
